### ISSUE TITLE
Example Success Call or Failure Call

### ISSUE THREAD

**Issue by zdharmawan** [audit4j/audit4j-demo#1]
Hi there,

Could you maybe also add an example to distinguish between success call or failing call?
Because as far as I know, audit4J will just audit as is without knowing it's throwing exception or not (for example). Thanks.

Regards,

Zul

**Comment by franck-benault** [comment]
Sorry there won't be any example (for version 2.5.0 and below)

because in the current implementation (2.5.0 and below), with the annotation @Audit,
there is no way to know if the method audited is ended correctly of if it is throwing an exception
 
One work arround is may be to call manually the  Audit Manager at the end of the method you want to audit (see doc 5.1 Calling Audit Manager)
But this solution is not always correct (transactionnal method with an error during the commit)

Regards Franck
